name: Test and build

on:
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i -g pnpm && pnpm i
      - name: Check types
        run: pnpm check
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          path: |
            .
            !node_modules
            !coverage
          retention-days: 1